import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Hero, HeroContent } from "../components/Hero";
import Navbar from "../components/Navbar";
import { FaPlay } from "react-icons/fa";
import HappyGirl from "../images/happy-girl.png";
import Section01 from "../sections/Section01";
import Section02 from "../sections/Section02";
import Section03 from "../sections/Section03";
import Section04 from "../sections/Section04";
import Section05 from "../sections/Section05";
import Footer from "../components/Footer";
export default function Home() {
  return (
    <div
      className={""}
      style={{
        background: "#fff",
      }}
    >
      <Head>
        <title>STAHOS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="mast-head">
        <div className="container">
          <Navbar />
          <Hero>
            <HeroContent>
              <aside className="side-one">
                <p className="captive-text">
                  Best Destinations around the world
                </p>
                <h1>Travel, enjoy and live a new and full life</h1>
                <p>
                  Built Wicket longer admire do barton vanity itself do in it.
                  Preferred to sportsmen it engrossed listening. Park gate sell
                  they west hard for the.
                </p>
                <div className="hero-buttons">
                  <Link href="/about">
                    <a className="btn btn-primary">Find out more</a>
                  </Link>

                  <button className="rounded-btn">
                    <FaPlay />
                  </button>
                  <span>Play Demo</span>
                </div>
              </aside>
              <aside className="side-two">
                <Image alt="happy girl" src={HappyGirl} />
              </aside>
            </HeroContent>
          </Hero>
        </div>
      </header>
      <main className={"main"}>
        <Section01 />
        <Section02 />
        <Section03 />
        <Section04 />
        <Section05 />
      </main>

      <Footer />
    </div>
  );
}
